/mv_camera:
  ros__parameters:
    camera_name: mv_camera

    analog_gain: 10
    exposure_time: 5000
    gamma: 100

    rgb_gain:
      b: 90
      g: 90
      r: 110

    saturation: 100


/armor_detector:
  ros__parameters:
    use_depth: false
    subscribe_compressed: false

    preprocess:
      hmin: 90
      lmin: 165
      smin: 100

    light:
      max_angle: 40.0
      max_ratio: 0.6
      min_ratio: 0.1

    armor:
      max_angle: 35.0
      max_center_ratio: 1.6
      min_center_ratio: 0.4
      min_light_ratio: 0.6
