/camera/camera:
  ros__parameters:
    enable_color: true
    color_width: 848
    color_height: 480
    color_fps: 60.0
    color_qos: SENSOR_DATA

    rgb_camera:
      auto_exposure_priority: false
      enable_auto_exposure: false
      exposure: 100
      saturation: 75

    enable_depth: true
    depth_width: 848
    depth_height: 480
    depth_fps: 60.0
    depth_qos: SENSOR_DATA
    align_depth: true
    
    enable_gyro: true
    enable_accel: true
    unite_imu_method: copy

    enable_infra: false
    enable_infra1: false
    enable_infra2: false
    enable_pointcloud: false
    enable_pose: false

    enable_sync: true
    publish_tf: true
    initial_reset: true

