name: PIONEER Vision CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup ROS 2
        uses: ros-tooling/setup-ros@v0.2
        with:
          required-ros-distributions: galactic

      - name: Build rm_serial_driver and run tests
        uses: ros-tooling/action-ros-ci@v0.2
        with:
          package-name: rm_serial_driver
          import-token: ${{ secrets.PAT }}
          target-ros2-distro: galactic

  build-and-push-image:
    needs: build-and-test
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true
          token: ${{ secrets.PAT }}

      - name: Unset AUTHORIZATION
        run: git config --local --unset http.https://github.com/.extraheader

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/chenjunnn/rm_pioneer_vision:latest
